# Generated by Django 5.1.2 on 2024-11-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
