# Generated by Django 5.1.5 on 2025-01-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_colorscheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык программирования', 'verbose_name_plural': 'Языки программирования'},
        ),
        migrations.AddField(
            model_name='language',
            name='code_example',
            field=models.TextField(blank=True, default='# Пример кода временно недоступен', help_text='Демонстрационный пример кода на языке', null=True, verbose_name='Пример кода'),
        ),
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.TextField(default='Описание языка программирования временно недоступно.', help_text='Краткое описание языка программирования', verbose_name='Описание языка'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
